### ISSUE TITLE
Sticky Sidebar Navigation is not working on GitHub Pages

### ISSUE THREAD

**Issue by debashis-biswal** [CloudCannon/base-jekyll-template#22]
I have hosted Jekyll site using bese-jekyll-template on github pages. But the sticky sidebar navigation is not working. Any Idea to resolve this? Is there any way to use custom plugins for github pages ?

**Comment by debashis-biswal** [comment]
Closed this issue as issue has been fixed.

**Comment by coolbrg** [comment]
Just curious to know how you have fixed this issue @debashis-biswal .

**Comment by magdmartin** [comment]
same here interested to see the sidebar can be displayed on Github pages.

**Comment by martinrefinepro** [comment]
As mention in #26 GitHub pages does not support custom plugin
You can do that by replacing TOC with a github compatible TOC generator. I used https://github.com/allejo/jekyll-toc

* Download the `toc.html` file from the latest release or the master branch
* Toss that file in your `_includes` folder.
* Edit `_layout/post.html`  and replace[ lines 8 to 10](https://github.com/CloudCannon/base-jekyll-template/blob/master/_layouts/post.html#L8) with `{% include toc.html html=content %}` 
* To keep things clean you can also the `'jekyll-extract-element'` from your Gemfile
