### ISSUE TITLE
File not found when click category link 

### ISSUE THREAD

**Issue by congto** [CloudCannon/base-jekyll-template#3]
Dear you !

I fork jekyll them  https://github.com/vietevo/vietevo.github.io and config `url: "https://vietevo.github.io/"` value in `__config.yml`. 

Then i access link `https://vietevo.github.io/`, it is ok. But, when click link https://vietevo.github.io/category/billing/`, result http://prntscr.com/emzjxu.

I try `https://orange-ape.cloudvent.net/category/account-settings/`. It is ok. 

Can you guide for me and fix.

Thanks

**Comment by mneumegen** [comment]
Hi @congto ,

The problem is GitHub Pages doesn't support the jekyll-archives plugin - https://github.com/jekyll/jekyll-archives/issues/60. I'd recommend getting in touch with their support - support@github.com.
