### ISSUE TITLE
Categories page doesn't work

### ISSUE THREAD

**Issue by ares-b** [CloudCannon/base-jekyll-template#34]
Hello,

Im trying to use this template for my blog but i can't get the blog pages to work.

https://dataengineers.me/category/account-settings/

Regards,

**Comment by bglw** [comment]
👋  Hi

Do you have a sample repository where this is happening? Spinning up a new base template for me shows categories working: https://lumpy-harmonica.cloudvent.net/category/deployment/

**Comment by ares-b** [comment]
Hi,

Im trying to deploy it using GitHub Pages not Cloudvent. I guess this template used some Jekyll plugin that can't be used in github because it works on local computer.

Is there anyway to make this work with github pages?

**Comment by bglw** [comment]
I think those archive pages are a result of the `jekyll-archive` plugin, which doesn't seem to be supported in GitHub Pages.

I think the usual course of action here is to use a GitHub Action to build a Jekyll site and push it to GitHub Pages — something like https://github.com/limjh16/jekyll-action-ts or https://github.com/helaili/jekyll-action would be good places to start. It isn't a flow I have used personally, sorry, so I can't be of much more help.

**Comment by deepakmahakale** [comment]
Made it work using https://github.com/marketplace/actions/jekyll-deploy-action
