### ISSUE TITLE
Sticky Sidebar Navigation is not working.

### ISSUE THREAD

**Issue by xqsit94** [CloudCannon/base-jekyll-template#6]
I forked this repo, but when I visit post page the sidebar navigation doesn't shows anything. It return empty result.

```
<section class="sidebar sticky">
    <ul>
        {% assign sub_navigation = content | extract_element: 'h2' %}
        {% for item in sub_navigation %}
            <li><a href="#{{ item.id }}">{{ item.text }}</a></li>
        {% endfor %}
    </ul>
</section>
```

But it works well on your demo site.

**Comment by mneumegen** [comment]
Hi @xqsit94,

Are you running this on GitHub Pages? We use a plugin to pull out the h2's, GitHub Pages doesn't support custom plugins. 

You'll need to rewrite this part to work without plugins.
